### ISSUE TITLE
Summary data table

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#12]
![image](https://cloud.githubusercontent.com/assets/793847/17818514/ed5dd80e-6611-11e6-8fbc-9fcd7b4a33e6.png)

**Comment by pbeshai** [comment]
Large numbers should be formatted (e.g. test count should look like 58,321 instead of 58321).

**Comment by pbeshai** [comment]
Consider putting location as bottom data?

![image](https://cloud.githubusercontent.com/assets/793847/18325644/2e83c25a-7510-11e6-8729-86e589d08626.png)

**Comment by vlandham** [comment]
seems logical.
