### ISSUE TITLE
Sort out "default location" for location page

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#144]
- currently defaults to Seattle
  - options: 
    - store last used location in cookie?
    - use HTML5 get location

> "once I select a location, that is a preference for me as I click to different views-- location, compare, data-- until I select a new location."

**Comment by vlandham** [comment]
I think it would be interesting to do html5 location. my worry is that the ui is frustrating - and still has edge cases where users select 'block' on the get location request.


Other options brainstorm:
* have a drop down on click that provides location search in nav bar on click
* have 'root location page' that has location search similar to home page
* remove 'home' link and make current home page the 'root location page' - and navigate there when 'locations' is clicked.
