### ISSUE TITLE
Front page map needs legend

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-client#215]
Need legend to show:

- [x] what servers look like
- [x] what test sources look like
- [x] color significance

**Comment by vlandham** [comment]
we have started this - check some of the closed PRs'

**Comment by vlandham** [comment]
Here is the current version. "legend" is text based, on the bottom. 

<img width="1223" alt="screen shot 2016-10-21 at 9 05 50 am" src="https://cloud.githubusercontent.com/assets/9369/19605198/a363b2fe-976d-11e6-8bcc-2810198afb20.png">

**Comment by pbeshai** [comment]
Irene feels this is insufficient. At the very least make the text colored where it says red and blue
