### ISSUE TITLE
Total test counts should be displayed for selected time range

### ISSUE THREAD

**Issue by vlandham** [bocoup/mlab-vis-client#241]
Should show total test counts for:

* current region
* selected isps

**Comment by pbeshai** [comment]
After some discussion what we will do is adjust the test counts in these charts:

![image](https://cloud.githubusercontent.com/assets/793847/19899090/1f3e6dd6-a035-11e6-9f8e-b76265660483.png)

They currently show the total for the selected ISPs. What we want is to show the total for the location AND the total for the selected ISPs. On hovering over an ISP name, show the total for the location and that ISP's count (but *not* the total for all selected).

**Comment by pbeshai** [comment]
Initial suggestion of using a table to show total sums of all tests for the time region was rejected. The idea was you could show this table and then have an option to expand it to show individual rows for each of the dates, making the numbers more accessible.

![image](https://cloud.githubusercontent.com/assets/793847/19899140/4fa68468-a035-11e6-9173-3c2021ac4e0b.png)
