### ISSUE TITLE
Don't repopulate client ISP list when all have been removed

### ISSUE THREAD

**Issue by vlandham** [bocoup/mlab-vis-client#28]
The user removed them for a reason. 
it is unkind to add them back.

![keep_them_out](https://cloud.githubusercontent.com/assets/9369/18099048/a6b360d2-6e99-11e6-9943-1ca4a88aefe9.gif)

**Comment by pbeshai** [comment]
This is interesting. The problem is in LocationPage's fetchData function:

```js
    // setup selected ISPs if needed
    if (topClientIsps && topClientIsps.length) {
      // if we don't have selected client ISPs yet, select the top ones.
      if (!selectedClientIspIds) {
        // once we have the client ISPs for the location, if we don't have selected client ISPs,
        // set the selected client ISPs to the top 3 for the location.
        const newSelectedIsps = [];
        topClientIsps.slice(0, 3).forEach(clientIsp => {
          const clientIspId = clientIsp.client_asn_number;
          newSelectedIsps.push(clientIspId);
        });
        dispatch(LocationPageActions.changeSelectedClientIspIds(newSelectedIsps));
      }
    }
```

Once they are all removed, selectedClientIspIds becomes `undefined` and so we re-run the changeSelectedClientIspIds action.

**Comment by pbeshai** [comment]
I think the "right" thing to do in this case is to allow "empty array" as a valid value for the URL decoding so we get `?isps=` in the URL which corresponds to []
