### ISSUE TITLE
When an error occurs, the UI continuously tries to fetch

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#41]
This is a side effect of how we handle fetchIfNeeded, since we say yes go fetch if there is an error. Should have some limit on retries before error is a dont-go-refetch problem.

**Comment by vlandham** [comment]
a simple (verbose) option is to add `retryCount` to each subsection of the redux tree store - parallel to `isFetched`. The `fetchIfNeeded` functions would check this count before returning true - to limit the times we try to get the api call.

**Comment by pbeshai** [comment]
We decided to make errors count as fetched data so we don't continuously try to fetch it.
