### ISSUE TITLE
Question: Height of small multiple

### ISSUE THREAD

**Issue by vlandham** [bocoup/mlab-vis-client#46]
Should small multiple component be provided a height and constrain the rows of charts to fit within  that height (as other components are implemented)?

or should the component grow and shrink given the number of clientISPs that are being displayed (as we originally envisioned)?

Current implementation follows the former option.

**Comment by pbeshai** [comment]
As I mentioned in slack, I think they should have a fixed height for each chart and it just gets taller if there are more rows.

**Comment by vlandham** [comment]
+1. i modified to use that approach with `chartHeight`
