### ISSUE TITLE
Adjust styling of small multiples time series

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#49]
Currently:
![image](https://cloud.githubusercontent.com/assets/793847/18291384/74b3d28a-7455-11e6-82ba-0d8ef2ef557b.png)

I think it should have the names closer to the axis lines and the headers should be left aligned. Or maybe the names go above the charts. Not sure, but we should play around

**Comment by pbeshai** [comment]
One possible version (not perfect):
<img width="748" alt="screen shot 2016-09-06 at 5 18 50 pm" src="https://cloud.githubusercontent.com/assets/793847/18291986/ec65777c-7458-11e6-97a7-1d1ce22a1a98.png">

**Comment by iros** [comment]
Trying different approaches:

A:
![image](https://cloud.githubusercontent.com/assets/18690/18317817/3dc1abe2-74ed-11e6-9eaf-5a291f319713.png)

B:
![image](https://cloud.githubusercontent.com/assets/18690/18317832/4bc57bba-74ed-11e6-944f-b0295638cc4c.png)

**Comment by vlandham** [comment]
can we try still on bottom but closer to the baseline - now that we have it?

**Comment by pbeshai** [comment]
Like the one I posted @vlandham in my comment https://github.com/bocoup/mlab-vis-client/issues/49#issuecomment-245104587
