### ISSUE TITLE
Test count bar chart

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#5]
![image](https://cloud.githubusercontent.com/assets/793847/17818433/8b66cff2-6611-11e6-8d3e-1468394be9a5.png)

**Comment by pbeshai** [comment]
I like the idea of the count chart being gray with a single value displayed on hover in color. The problem with them being stacked and colored to begin with is that on hover, if you gray out all but one, the boxes will be all at different heights and it will be difficult to compare against.

![image](https://cloud.githubusercontent.com/assets/793847/17855970/4df5b52c-6849-11e6-868b-f70ec7ddc4c0.png)

**Comment by vlandham** [comment]
yep. i like it. 
this is what i had in mind as well.
