### ISSUE TITLE
line charts need ISP legend

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-client#54]

**Comment by vlandham** [comment]
This needs to be considered along with #30

**Comment by vlandham** [comment]
So in our original - the lines on the y axis had a permanent label on the right hand side.

<img width="114" alt="screen shot 2016-09-07 at 8 51 24 am" src="https://cloud.githubusercontent.com/assets/9369/18318911/56acda6a-74d8-11e6-9050-af8067ee68e4.png">

My idea was that we could use some trickery to prevent occlusion. 
These labels would do even better if they incorporated the color of the line somehow. either in font color or little connecting lines or something

**Comment by vlandham** [comment]
This is one example of label placement trickery i was thinking about

https://github.com/tinker10/D3-Labeler

there is another that uses force layout - but i think that is overkill for what we have.

**Comment by vlandham** [comment]
while slightly clunky - i like nvd3's mouse over on multiple lines. 
http://nvd3.org/

<img width="456" alt="screen shot 2016-09-07 at 9 06 43 am" src="https://cloud.githubusercontent.com/assets/9369/18319400/6c3cbe20-74da-11e6-8de3-289ebe9ededb.png">

Show a vertical bar where the mouse is at. Display values for all lines. 

I like @pbeshai 's charts with the location of these values in the top-right corner of the graph. 

In my head this could work in tandem with the right-labels. With perhaps the right labels fading away on mouse over. maybe not.

**Comment by iros** [comment]
Could you color these?

![image](https://cloud.githubusercontent.com/assets/18690/18321709/28572a7e-74fd-11e6-9907-c7379015ae85.png)

**Comment by vlandham** [comment]
yes definitely. that is why #30 should be part of this as well.

**Comment by pbeshai** [comment]
### Legends

Some of these names for legends are really damn long so I don't think our mockups will work well. I think for the time series and hourly charts we should consider placing the legend at the bottom beneath the counts histogram where the names are listed with a color box next to them (and HEY maybe you can click the color box to change it ;D). Do it in a display inline-block way so you get something like:

```
[#00f] Comcast Cable Communicatinos, Inc.     [#f00] AT&T Services, Inc.    [#0f0] Commnuications Services, Inc. d/b/a Verizon
```

And it just expands to fill the the space. 

The problem with stacking them vertically on the right is that they are so damn wide, so you lose a lot of chart space or you truncate the names.

The problem with stacking them vertically at the bottom is that you add a lot of whitespace between charts.

Alternatively we show a truncated legend on the right and then when you hover over a line or over the entry in the legend you see the full name. 

### Tooltip

As for the tooltip, it's nice and convenient showing values right beside legend entries, but you don't really want to look to far away from the mouse. I decided to solve it this way in Buckets:

![image](https://cloud.githubusercontent.com/assets/793847/18324940/f7c8bb92-750c-11e6-9161-904331217b43.png)

**Comment by pbeshai** [comment]
As per external discussion: going to try with legends above the charts with tooltips as a line that follows the mouse. Values from the tooltips will be shown in the legend (static location). Names in the legend will have a fixed width and be truncated, revealed on hover.
