### ISSUE TITLE
adjust y extent to be the same for both download and upload speeds for multi-line charts

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-client#55]

**Comment by vlandham** [comment]
Another approach would be to still have 2 set extents for upload and download - but to have some visible axes ticks that run along the width of the main chart. 

toggling between upload and download (and the rest of the metrics) would animate these ticks - to show the relation between the two charts. 

this would allow us to have more specific scales for the two metrics - and would help in situations where an observation extends past the preset extent - and we have to change the extent to show it.

**Comment by vlandham** [comment]
somewhat similar to : http://bl.ocks.org/mbostock/4323929
