### ISSUE TITLE
Time range picker

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#6]
![image](https://cloud.githubusercontent.com/assets/793847/17818443/96e60cbc-6611-11e6-9655-40faa974b50e.png)

![image](https://cloud.githubusercontent.com/assets/793847/17818543/1c593ba8-6612-11e6-83ab-85622e29c602.png)

**Comment by vlandham** [comment]
Inspiration / Options to consider:

[Airbnb react-dates](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=default&full=0&down=1&left=1&panelRight=0)

[React Date Picker](https://github.com/zippyui/react-date-picker)

[react date range picker](http://onefinestay.github.io/react-daterange-picker/)

**Comment by vlandham** [comment]
See #35
