### ISSUE TITLE
When reducing time range, then hovering over legend, the line extends beyond the y axis

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-client#85]
![image](https://cloud.githubusercontent.com/assets/18690/18562080/52d02216-7b50-11e6-8a5f-b3eaf17a6fc8.png)

**Comment by pbeshai** [comment]
I am not able to reproduce this right now. Can you confirm it still happens @iros?

**Comment by iros** [comment]
I can't reproduce anymore. Closing.
