### ISSUE TITLE
Standardize chart component area names

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-client#94]
![image](https://cloud.githubusercontent.com/assets/793847/18638749/446c9d0a-7e5f-11e6-9e92-70cc3fb44ebe.png)

- `innerWidth` -> `plotAreaWidth`
- `innerHeight` -> `plotAreaHeight`
- `innerMargin` -> `padding`

**Comment by iros** [comment]
Fixed. Closing.
